### PR TITLE
feat: implement Onboard page

### PR DESCRIPTION
**Pull request by martinvibes**
hey @faytey @Goodness5 kindly review :)

### CODE REVIEW

**Review by faytey — CHANGES_REQUESTED** [review]
the app breaks after the flash screen loads and also doesn't load up wallets , kindly fix the issues and also send a screenshot or video of the final working application
IMG_5473
IMG_5474

**Comment by martinvibes** [comment]
alright @faytey  i'm working on it now

**Comment by martinvibes** [comment]
so @faytey i think you need to get a projectId for Appkit at Reown for the wallet kit

**Comment by faytey** [comment]
> so @faytey i think you need to get a projectId for Appkit at Reown for the wallet kit

Kindly send a screenshot or video of the working model from your local machine

**Comment by martinvibes** [comment]
it now works @faytey 


https://github.com/user-attachments/assets/3efb3b4f-99aa-4db6-bddd-a9a72801a8d2




https://github.com/user-attachments/assets/c0909226-d63a-43d4-b392-77dd04b4d94f

**Review by faytey — APPROVED** [review]

**Pull request merged**
